env:
  global:
      # Daily commit is used on master branch and build commit on named
      # branches
      - BUILD_COMMIT=1.3.0
      - DAILY_COMMIT=master
      - REPO_DIR=kiwi
      - PLAT=x86_64
      - UNICODE_WIDTH=32
      - CIBW_TEST_REQUIRES=pytest
      - CIBW_TEST_COMMAND=python -m pytest {package}/tests -v

language: python
# Default Python version is usually 2.7
python: "3.8"
services: docker

jobs:
  include:
    - os: linux
      arch: arm64
      env:
        - CIBW_BUILD=3.6
    - os: linux
      arch: arm64
      env:
        - CIBW_BUILD=3.7
    - os: linux
      arch: arm64
      env:
        - CIBW_BUILD=3.8
    - os: linux
      arch: arm64
      env:
        - MB_ML_VER=2014
        - CIBW_BUILD=3.9

before_install:
    - if [ "$TRAVIS_BRANCH" == "master" ]; then
          BUILD_COMMIT=${DAILY_COMMIT:-$BUILD_COMMIT};
      fi
    - git submodule update --init
    - git checkout $BUILD_COMMIT

install:
    - python -m pip install --upgrade pip
    - python -m pip install wheel cibuildwheel

script:
    - python -m cibuildwheel kiwi --output-dir ~/dist

after_success:
    # The tokens are set from
    # https://anaconda.org/multibuild-wheels-staging/settings/
    - if [ "$TRAVIS_BRANCH" != "master" ] ; then
          ANACONDA_ORG="multibuild-wheels-staging";
          TOKEN=${KIWI_STAGING_UPLOAD_TOKEN};
      fi
    - pip install git+https://github.com/Anaconda-Server/anaconda-client;
    - which python
    - if [ -n "${TOKEN}" ] ; then
        anaconda -t ${TOKEN} upload --force -u ${ANACONDA_ORG} ${TRAVIS_BUILD_DIR}/wheelhouse/*.whl;
      fi
