env:
  global:
      # Daily commit is used on master branch and build commit on named
      # branches
      - BUILD_COMMIT=1.3.0
      - DAILY_COMMIT=master
      - REPO_DIR=kiwi
      - PLAT=x86_64
      - UNICODE_WIDTH=32
      - WHEELHOUSE_UPLOADER_USERNAME=travis-worker

language: python
# Default Python version is usually 2.7
python: "3.7"
services: docker

jobs:
  include:
    - os: linux
      arch: arm64
      env:
        - PLAT=aarch64
        - MB_ML_VER=2014
        - MB_PYTHON_VERSION=3.6
        - DEBUG_PRINT=1
        - DOCKER_TEST_IMAGE=multibuild/xenial_{PLAT}
    - os: linux
      arch: arm64
      env:
        - PLAT=aarch64
        - MB_ML_VER=2014
        - MB_PYTHON_VERSION=3.7
        - DEBUG_PRINT=1
        - DOCKER_TEST_IMAGE=multibuild/xenial_{PLAT}
    - os: linux
      arch: arm64
      env:
        - PLAT=aarch64
        - MB_ML_VER=2014
        - MB_PYTHON_VERSION=3.8
        - DEBUG_PRINT=1
        - DOCKER_TEST_IMAGE=multibuild/xenial_{PLAT}
    - os: linux
      arch: arm64
      env:
        - PLAT=aarch64
        - MB_ML_VER=2014
        - MB_PYTHON_VERSION=3.9
        - DEBUG_PRINT=1
        - DOCKER_TEST_IMAGE=multibuild/xenial_{PLAT}

before_install:
    - if [ "$TRAVIS_BRANCH" == "master" ]; then
          CONTAINER="pre-release";
          BUILD_COMMIT=${DAILY_COMMIT:-$BUILD_COMMIT};
      else
          CONTAINER=wheels;
          UPLOAD_ARGS="--no-update-index";
      fi
    - source multibuild/common_utils.sh
    - source multibuild/travis_steps.sh
    - before_install

install:
    # Maybe get and clean and patch source
    - clean_code $REPO_DIR $BUILD_COMMIT
    - build_wheel $REPO_DIR $PLAT

script:
    - install_run $PLAT

after_success:
    # The tokens are set from
    # https://anaconda.org/multibuild-wheels-staging/settings/
    - if [ "$TRAVIS_BRANCH" != "master" ] ; then
          ANACONDA_ORG="multibuild-wheels-staging";
          TOKEN=${KIWI_STAGING_UPLOAD_TOKEN};
      fi
    - which pip
    - which python
    - pip install git+https://github.com/Anaconda-Server/anaconda-client;
    - python -V
    - if [ -n "${TOKEN}" ] ; then
        anaconda -t ${TOKEN} upload --force -u ${ANACONDA_ORG} ${TRAVIS_BUILD_DIR}/wheelhouse/*.whl;
      fi