# vim ft=yaml
# CI on Windows via appveyor

environment:
  global:
    BUILD_COMMIT: 1.2.0
    KIWI_STAGING_UPLOAD_TOKEN:
      secure: hYPQXkQO2G7bXy9XYRlU64WjapLtv7KPYSIpt9GZX3JaS4jlfnNhkCCeGPVh8bj5

  matrix:
    - PYTHON: C:\Python36
    - PYTHON: C:\Python36-x64
    - PYTHON: C:\Python37
    - PYTHON: C:\Python37-x64
    - PYTHON: C:\Python38
    - PYTHON: C:\Python38-x64
    - PYTHON: C:\Python39
    - PYTHON: C:\Python39-x64

install:
  - git submodule update --init
  # Install new Python if necessary
  - ps: .\multibuild\install_python.ps1

  # Prepend newly installed Python to the PATH of this build (this cannot be
  # done from inside the powershell script as it would require to restart
  # the parent CMD process).
  - SET PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%
  - python -m pip install -U pip

  # Fix MSVC builds for 64-bit Python. See:
  # http://stackoverflow.com/questions/32091593/cannot-install-windows-sdk-7-1-on-windows-10
  - echo "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64 > "C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\bin\amd64/vcvars64.bat"

  # Pin wheel to 0.26 to avoid Windows ABI tag for built wheel
  - pip install wheel==0.26
  # Build wheel
  - cd kiwi
  - git checkout %BUILD_COMMIT%
  - python setup.py bdist_wheel
  - cd ..

build: false  # Not a C# project, build stuff at the test step instead.

test_script:
  - pip install --pre --no-index --find-links .\kiwi\dist kiwisolver
  - pip install pytest
  # Change into an innocuous directory and find tests from installation
  - mkdir for_testing
  - cd for_testing
  - python --version
  - py.test ..\kiwi
  - cd ..

artifacts:
  # Archive the generated wheel package in the ci.appveyor.com build report.
  - path: kiwi\dist\*

on_success:
  # Upload the generated wheel package to anaconda.org
  # KIWI_STAGING_UPLOAD_TOKEN is an encrypted variable
  # used in Appveyor CI config, originally created at
  # multibuild-wheels-staging site
  - cd ..\kiwi
  - cmd: set ANACONDA_ORG="multibuild-wheels-staging"
  - pip install git+https://github.com/Anaconda-Server/anaconda-client
  - IF NOT "%KIWI_STAGING_UPLOAD_TOKEN%" == "" anaconda -t %KIWI_STAGING_UPLOAD_TOKEN% upload --force -u %ANACONDA_ORG% "dist\*.whl"

cache:
  # Use the appveyor cache to avoid re-downloading large archives such
  # the MKL numpy and scipy wheels mirrored on a rackspace cloud
  # container, speed up the appveyor jobs and reduce bandwidth
  # usage on our rackspace account.
  - '%APPDATA%\pip\Cache'
