name: Build wheels

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }} for Python ${{ matrix.python }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        python: [38]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - name: Install cibuildwheel
        run: |
          python -m pip install cibuildwheel==1.6.3
      - name: Build wheels
        env:
          CIBW_BUILD: cp${{ matrix.python }}-*
        run: |
          python -m cibuildwheel kiwi --output-dir wheelhouse
      - name: Store artifacts
        uses: actions/upload-artifact@v2
        with:
          path: wheelhouse/*.whl

  upload_anaconda:
    name: Upload to Anaconda
    runs-on: ubuntu-latest
    needs: [build_wheels]
    steps:
      - name: Download artifacts
        uses: actions/download-artifacts@v2
        with:
          path: dist
      - name: Display artifacts
        run: |
          ls -l dist/*
