name: Build and upload wheels
on: [push, pull_request]

jobs:

  build_wheels:
    name: Build wheels on ${{ matrix.os }} for Python ${{ matrix.python }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python: [36]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Update repo
        env:
          BUILD_COMMIT: 1.3.0
        run: |
          git submodule update --init
          cd kiwi
          git checkout $BUILD_COMMIT
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install cibuildwheel
        run: |
          python -m pip install --upgrade pip
          python -m pip install wheel cibuildwheel
      - name: Build wheels
        env:
          CIBW_BUILD: cp${{ matrix.python }}-*
          CIBW_TEST_REQUIRES: pytest
          CIBW_TEST_COMMAND: python -m pytest {package}/py/tests -v
        run: |
          python -m cibuildwheel kiwi --output-dir dist
      - name: Store artifacts
        uses: actions/upload-artifact@v2
        with:
          name: artifact
          path: dist/*.whl

  upload_anaconda:
    needs: [build_wheels]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: artifact
          path: dist
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Anaconda upload
        if: "!contains( github.ref, 'master')"
        env:
          ANACONDA_ORG: multibuild-wheels-staging
        run: |
          python -m pip install pip --upgrade
          pip install git+https://github.com/Anaconda-Server/anaconda-client
          anaconda --token ${{ KIWI_STAGING_UPLOAD_TOKEN }} upload --force -u ${ANACONDA_ORG} dist/*.whl
